---
branches: main

variables:
  surge_settings: &surge_settings
    path: public
    surge_token:
      from_secret: SURGE_TOKEN
    forge_type: gitea
    forge_url: https://git.shrug.pw
    forge_repo_token: 
      from_secret: SURGE_GITEA

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

pipeline:
  build:
    image: registry.gitlab.com/pages/hugo/hugo_extended:latest
    commands:
      - hugo

  preview:
    image: woodpeckerci/plugin-surge-preview
    secrets: [SURGE_TOKEN, SURGE_GITEA]
    settings: *surge_settings
    when:
      event: pull_request

  teardown-preview:
    image: woodpeckerci/plugin-surge-preview
    secrets: [SURGE_TOKEN, SURGE_GITEA]
    settings: *surge_settings
    environment:
      - CI_BUILD_EVENT=pull_close
    when:
      event: pull_close

  publish:
    image: git.shrug.pw/neil/containers/woodpecker-ci:latest
    secrets: [ssh_key, GITLAB_DEPLOY_TOKEN]
    environment:
      - GIT_AUTHOR_NAME="Woody the Woodpecker"
      - GIT_AUTHOR_EMAIL=ci@shrug.pw
    commands:
      - mkdir -p  ~/.ssh/
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 0700 ~/.ssh/
      - chmod 0600 ~/.ssh/id_rsa
      - bash deploy.sh
    when:
      branch: main
      event: [push]

